// src/agents/Aether.js
import axios from 'axios';
import RNHTMLtoPDF from 'react-native-html-to-pdf';

export class AetherAgent {
  constructor(apiBaseUrl = 'https://pap-crm.vercel.app/api') {
    this.apiBaseUrl = apiBaseUrl;
  }

  /**
   * Primary entry point for executing tasks delegated by Maya
   */
  async executeTask(packet) {
    try {
      switch (packet.actionType) {
        case 'QUERY_DATABASE':
          return await this.fetchCRMData(packet);

        case 'GENERATE_PDF':
          return await this.generatePdfReport(packet);

        default:
          return {
            taskId: packet.taskId,
            status: 'ERROR',
            errorMessage: `Unknown action type: ${packet.actionType}`,
          };
      }
    } catch (error) {
      return {
        taskId: packet.taskId,
        status: 'ERROR',
        errorMessage: error.message || 'Execution error in Aether module.',
      };
    }
  }

  /**
   * Database Fetch Execution
   */
  async fetchCRMData(packet) {
    const endpoint = packet.parameters.endpoint || 'leads';
    const response = await axios.get(`${this.apiBaseUrl}/${endpoint}`);

    return {
      taskId: packet.taskId,
      status: 'SUCCESS',
      dataPayload: response.data,
    };
  }

  /**
   * Local PDF Document Generation Execution
   */
  async generatePdfReport(packet) {
    const reportTitle = packet.parameters.title || 'Ogamoto CRM Executive Report';
    const reportData = packet.parameters.data || { "Pipeline Leads": 1540, "Sea Cargo Manifests": 389 };

    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: Helvetica, Arial, sans-serif; padding: 24px; color: #09090b; }
            h1 { color: #00E5FF; font-size: 22px; margin-bottom: 6px; }
            p { font-size: 12px; color: #555; margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; }
            th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; font-size: 13px; }
            th { background-color: #101014; color: #00E5FF; }
          </style>
        </head>
        <body>
          <h1>${reportTitle}</h1>
          <p>Generated by Aether Engine | Ogamoto CRM</p>
          <table>
            <tr><th>Metric / Data Field</th><th>Value</th></tr>
            ${Object.entries(reportData).map(([k, v]) => `<tr><td><b>${k}</b></td><td>${v}</td></tr>`).join('')}
          </table>
        </body>
      </html>
    `;

    const options = {
      html: htmlContent,
      fileName: `Ogamoto_Report_${Date.now()}`,
      directory: 'Documents',
    };

    const pdfFile = await RNHTMLtoPDF.convert(options);

    return {
      taskId: packet.taskId,
      status: 'SUCCESS',
      filePath: pdfFile.filePath,
      dataPayload: { message: 'PDF generated successfully' },
    };
  }
}
