// src/agents/Aether.js
import axios from 'axios';
import RNHTMLtoPDF from 'react-native-html-to-pdf';

export class AetherAgent {
  constructor(apiBaseUrl = 'https://api.yourcrm.com/v1') {
    this.apiBaseUrl = apiBaseUrl;
  }

  /**
   * Main entry point for executing tasks delegated by Maya
   */
  async executeTask(packet) {
    try {
      switch (packet.actionType) {
        case 'QUERY_DATABASE':
          return await this.fetchCRMData(packet);

        case 'GENERATE_PDF':
          return await this.generatePdfReport(packet);

        default:
          return {
            taskId: packet.taskId,
            status: 'ERROR',
            errorMessage: `Unknown action type: ${packet.actionType}`,
          };
      }
    } catch (error) {
      return {
        taskId: packet.taskId,
        status: 'ERROR',
        errorMessage: error.message || 'Execution failed inside Aether engine',
      };
    }
  }

  /**
   * Database / API Fetch Operation
   */
  async fetchCRMData(packet) {
    // Replace endpoint with your actual backend URL when ready
    const response = await axios.get(`${this.apiBaseUrl}/leads`, {
      params: packet.parameters,
    });

    return {
      taskId: packet.taskId,
      status: 'SUCCESS',
      dataPayload: response.data,
    };
  }

  /**
   * Local PDF Document Generation
   */
  async generatePdfReport(packet) {
    const reportData = packet.parameters.data || { Summary: "Q2 Performance Overview", Status: "Optimal" };
    
    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #1a202c; }
            h1 { color: #0d9488; font-size: 24px; margin-bottom: 8px; }
            p { font-size: 14px; color: #4a5568; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
            th { background-color: #f7fafc; color: #2d3748; }
          </style>
        </head>
        <body>
          <h1>Ogamoto CRM Executive Report</h1>
          <p>Generated by Aether Computational Engine</p>
          <table>
            <tr><th>Metric / Parameter</th><th>Value</th></tr>
            ${Object.entries(reportData).map(([key, val]) => `<tr><td><b>${key}</b></td><td>${val}</td></tr>`).join('')}
          </table>
        </body>
      </html>
    `;

    const options = {
      html: htmlContent,
      fileName: `Ogamoto_Report_${Date.now()}`,
      directory: 'Documents',
    };

    const pdfFile = await RNHTMLtoPDF.convert(options);

    return {
      taskId: packet.taskId,
      status: 'SUCCESS',
      filePath: pdfFile.filePath,
      dataPayload: { message: 'PDF generated successfully' },
    };
  }
}
